name: Test project

on: [push, pull_request]

jobs:
  testAllModes:
    name: Test in Play Mode only
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: game-ci/unity-test-runner@v2
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          testMode: PlayMode
          artifactsPath: PlayMode-artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: PlayMode Test Results
          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+my.assembly.*'
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results for PlayMode
          path: ${{ steps.tests.outputs.artifactsPath }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Coverage results for PlayMode
          path: ${{ steps.tests.outputs.coveragePath }}
    